services:
    encode_translatable_listener:
        class: TX3\DoctrineUtilBundle\EventListener\EncodeTranslationListener
        tags:
          - {name: doctrine.event_listener, event: preUpdate}
        arguments: [@annotation_reader, %tuxes3_doctrine_util.config%]

    decode_translatable_listener:
        class: TX3\DoctrineUtilBundle\EventListener\DecodeTranslationListener
        tags:
          - {name: doctrine.event_listener, event: postLoad}
        arguments: [@annotation_reader,%tuxes3_doctrine_util.config%]

    kernel_request.listener:
        class: TX3\DoctrineUtilBundle\EventListener\KernelRequestListener
        tags:
            - { name: kernel.event_listener, method: onKernelRequest, event: kernel.request }
        arguments: [@decode_translatable_listener, @encode_translatable_listener]

    type.translation:
        class: TX3\DoctrineUtilBundle\Form\Type\TranslationType
        tags:
            - { name: form.type, alias: translation }